config/routes.rb
Rails.application.routes.draw do
  resources :hobbies
  resources :blog_tags
  resources :tags
  resources :categories
  resources :likes, only: [:create, :destroy]
  resources :blogs do
    resources :comments, only: [:create]
  end
  devise_for :users
  get 'blogs/categories/:category_id', to: 'blogs#show_category', as: :show_blogs_category
  get 'blogs/tags/:tag_id', to: 'blogs#show_tag', as: :show_blogs_tag

  root 'blogs#index'

  namespace :admin do
    resources :users
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

    validates :title, presence: true, uniqueness: { case_sensitive: true }, length: {maximum: 50, minimum:5}
    validates :body, presence: true, uniqueness: { case_sensitive:  true }, length: { minimum: 10 }
    validate :correct_image_type

    belongs_to :user
    belongs_to :category
    has_many_attached :images

    has_many :blog_tags
    has_many :tags, through: :blog_tags

    has_many :likes
    has_many :comments

    def correct_image_type
        if images.attached? == false
            errors.add(:images, "are missing")
        end

        images.each do |image|
            if !image.content_type.in?(%w(image/jpeg image/png))
                errors.add(:image,"must be a JPG/JPEG/PNG")
            end
        end
    end
#   accepts_nested_attributes_for :tag, allow_destroy: true

    def tags_attributes=(tags_attributes)
        tags_attributes.values.each do |tag|
            if !tag[:name].empty?
                self.tags << Tag.find_or_create_by(name: tag[:name])
            end
        end
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @q = Blog.ransack(params[:q])
    @blogs = @q.result(distinct: true).order(id: :desc).paginate(:page => params[:page], :per_page => 3)

    # @blogs = Blog.all
    @categories = Category.all
    @tags = Tag.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  def show_category
    @categories = Category.all
    @tags = Tag.all
    # @category = Category.where(id: params[:category_id]).first
    @category = Category.find(params[:category_id]) 
    @q = @category.blogs.ransack(params[:q])
    @blogs = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 3)
  end

  def show_tag
    @categories = Category.all
    @tags = Tag.all
    # @tag = Tag.where(id: params[:tag_id]).first
    @tag = Tag.find(params[:tag_id]) 
    @q = @tag.blogs.ransack(params[:q])
    @blogs = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 3)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    @blog.tags.build
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    if (@blog.user_id == current_user.id || current_user.role == "ADMIN")
      respond_to do |format|
        if @blog.update(blog_params)
          format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
          format.json { render :show, status: :ok, location: @blog }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to blogs_path,notice:"You are not allowed to edit this blog."
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :category_id,images: [],tags_attributes: [:id,:name], tag_ids: [])
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="card">
    <div class="card-body">
    <%= form_for blog do |form| %>
      <% if blog.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

          <ul>
            <% blog.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field form-group">
        <%= form.label :title %>
        <%= form.text_field :title ,class:"form-control"%>
      </div>

      <div class="field form-group">
        <%= form.label :body %>
        <%= form.text_area :body ,class:"form-control"%>
      </div>

      <div class="field form-group">
        <%= form.label :category %>
        <%= form.collection_select(:category_id, Category.all ,:id,:name,prompt: true) %>
        <%#= form.select :category_id, Category.all.map {|c| [c.name,c.id]} ,prompt: true%>
      </div>

      <div class="field form-group">
        <%= form.label :images %>
        <%= form.file_field :images , multiple: true %>
      </div>

      <div class="field form-group">
        <%= form.label :tags %>
        <%#= form.collection_check_boxes :tag_ids , Tag.all, :id , :name%>
        <%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <div class="form-check">
            <%= tag.check_box(class: "form-check-input") %>
            <%= tag.label(class: "form-check-label") %>
              <%= form.fields_for :tag ,blog.tags.build do |t| %>
                <%= t.text_field :name, :value=>tag.object.name %>
              <% end %>
          </div>
        <% end %>
        <br/>
        <div>
          <input type="button" id="btn" class="btn btn-outline-primary" value="Create a New Tag">
        </div>

        <div id="Create" style="display:none">
          <h4>or Create a Tag:</h4>
          <%= form.fields_for :tags, blog.tags.build do |t|%>
            <%= t.label :name %>
            <%= t.text_field :name %>
          <%end%>
        </div>

      </div>

      <div class="actions">
        <%= form.submit class:"btn btn-outline-success"%>
      </div>
    <% end %>
    </div>
    <%= link_to 'Back', blogs_path ,class:"btn btn-secondary h-25"%>
  </div>
</div>



<script type="text/javascript">
  $(document).ready(function () {
      $("#btn").click(function () {
          $("#Create").toggle();
      });
  });
</script>

app/views/blogs/_search_form.html.erb
<script type="text/javascript">
  function like_btn(like_id)
  {
    like = like_id.split('_')[1];
    console.log(like);
    div_show = "Create_"+like;
    console.log(div_show);
    x = document.getElementById(div_show);
    console.log(x.style.display);
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }

  }
</script>
<style>
  *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  .contain {
    display: flex;
  }
  .recent_post{
    width: 25%;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .all_blogs{
    width: 50%;
    padding: 0px 11px;

  }
  .category_tags{
    width: 25%;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .blog-card-body {
    width: 500px !important;
  }
  .tag-card {
    width: 250px !important;
  }
  .button-circle{
    line-height: 1.7em;
    border-radius: 50px;
  }
  .list-group{
    width: 210px;
  }
  .liked{
    background: transparent;
    border: none;
    color: #007bff;
    cursor: pointer;
  }
  .h-fit{
    height: fit-content;
  }
  @media (max-width: 986px) {
    body{
      background-color: palevioletred;
    }
    .contain {
    flex-direction: column;
    }
    .recent_post{
      width: 100%;
    }
    .all_blogs{
      width: 100%;
    }
    .category_tags{
      width: 100%;
    }
    .blog-card-body {
      width: 460px !important;
    }
    .tag-card {
      width: 100% !important;
    }
  }
  @media (max-width: 425px) {
    .all_blogs{
      width: 400px;
    }
    .blog-card-body {
      width: 400px !important;
    }
    .img-blogs{
      width: 370px !important;
    }
  }

</style>
<div class="contain">
  <div class = "recent_post">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>Recent Blogs</span></h4>
        </div>
        <div class="card-body">
          <ul class="list-group">
            <% @blogs.last(3).each do |blog|%>
              <li class="list-group-item d-flex align-items-center">
                <%= image_tag blog.images.first, class:"blog-img" ,width:"40px"%> 
                <%= link_to blog.title, blog, class:'link'%>
            <%end%>
              </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class = "all_blogs">
    <strong><%= params[:controller].capitalize%></strong>
    <strong><%= params[:action].capitalize%></strong>
    <% @blogs.each do |blog| %>
      <div class="card mb-3 ">
        <div class="img-card col col-md-4 col-sm-12">
          <% if blog.images.present?%>
            <%= image_tag blog.images.first, class:"blog-img img-blogs" ,width:"500px"%> 
          <%end%>
        </div>
        <div class="card-body blog-card-body">
          <h3 class="card-title font-weight-900"><%= blog.title %></h3>
          <p class="card-text">
            <div class="d-flex justify-content-between text-muted">
              <div>
                <p><i class="fa fa-user"></i> <%= blog.user.email %></p>
              </div>            
              <div>
                <p><i class="fa fa-calendar"></i> <%= find_date(blog.created_at) %></p>
              </div>            
            <div class="text-muted">
              <p>Category: <%= blog.category.name %></p>
            </div>
            </div>
          </p>
          <p class="card-text mb-5"><%= blog.body %></p>
          <hr>
          <div class="d-flex justify-content-between">
            <div>
              <div class="d-flex">
                <div class="h-fit">
                  <% like = current_user.likes.find_by(blog: blog) %>
                  <% if like.nil? %>
                    <%= button_to likes_path,class:"liked",params:{like:{blog_id: blog.id}},method: :post do %>
                      <i class="fa-regular fa-heart fa-2x"></i>
                    <% end %>
                  <% else %>
                    <%= button_to like_path(like),class:"liked",method: :delete do %>
                      <i class="fa-solid fa-heart fa-2x"></i>
                    <% end %>
                  <% end %>
                </div>
                <div class="px-3 py-1 h-fit">
                  <input type="button" id="btn_<%= blog.id %>" class="liked" onclick="like_btn(this.id)" value="<%=blog.likes.count%> Likes">
                </div>
                <div class="h-fit">
                  <p class="btn link m-auto py-1 px-3"><i class="fa-solid fa-comments"></i>
                  <%= blog.comments.count%>
                  </p>
                </div>
              </div>
              <div id="Create_<%= blog.id %>" style="display:none" class="card text-center">
                <div class="card-header">
                  Likes
                </div>
                <div class="card-body">
                  <% blog.likes.each do |l| %>
                    <p class="card-text"><%= l.user.email %></p>
                  <% end %>
                </div>
              </div>
            </div>
            <div>
              <p class="lead"><%= link_to 'Read More..', blog, class: "btn btn-primary read-btn"%></p>
            </div>
          </div>

          <% if user_signed_in? && ((blog.user_id == current_user.id)|| current_user.role=="ADMIN") %>
            <%= link_to 'Edit', edit_blog_path(blog), class: "link" %> | 
            <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "link" %>
          <% end %>       
        </div>
      </div>
    <% end %>
    <div class="row margin-twenty5-zero margin-b-zero pagination-row justify-content-between">
      <div class="col-lg-6 col-md-8 col-sm-7 col-xs-6 padding-zero">
        <ul class="pagination">
          <li class="page-item disabled"> <%= will_paginate(@blogs,:previous_label => "&laquo;", :next_label => "&raquo;",:class=>"large-font",:outer_window => 1,:inner_window => 0) %></li>
        </ul>
      </div>
      <div class="col-lg-6 col-md-4 col-sm-5 col-xs-6 pagination-info">
        <p class="pull-right large-font"><%= page_entries_info(@blogs) %></p>
      </div>
    </div>
    
  </div>
  <div class = "category_tags">
    <%# categories %>
    <div class="card w-50 p-3">
      <div class="card-header d-flex justify-content-between">
        <h4>Categories</span></h4> 
        <%= link_to new_category_path ,:class => "text-light btn btn-success button-circle" do%>
            <i class="fa-solid fa-plus"></i>
        <%end%>
      </div>
      <div class="card-body">
        <ul class="list-group">
          <% @categories.each do |category|%>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= link_to category.name, show_blogs_category_path(:category_id => category.id), class:'cat-link'%>
              <span class="badge badge-primary rounded-pill" ><%= category.blogs.count%></span>
            </li>
          <%end%>
        </ul>
        <%= link_to 'Add New Category', new_category_path, class: 'btn btn-outline-info'%>
      </div>
    </div>
    <%# Tags %>
    <div class="card w-50 p-3 tag-card">
      <div class="card-header">
        <h4>Tags</span></h4>
      </div>
      <div class="card-body">
          <% @tags.each do |tag|%>
            <%= link_to tag.name, show_blogs_tag_path(:tag_id => tag.id), class:"badge badge-secondary"%>
          <%end%>
      </div>
    </div>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="d-flex justify-content-center">
    <h1>Editing Blog</h1>
</div>
<%= render 'form', blog: @blog %>

app/views/blogs/index.html.erb
<%= render 'blogs/search_form.html.erb' %>

app/views/blogs/new.html.erb
<div class="d-flex justify-content-center">
    <h1>New Blog</h1>
</div>
<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-center"><%= @blog.title %></h1>
  <p>
    <strong>Created By:</strong>
    <%= @blog.user.email %>
  </p>
  <p>
    Created at : <%= find_date(@blog.created_at) %> <%= find_time(@blog.created_at) %>
  </p>
  <p>
    Updated at : <%= find_date(@blog.updated_at) %> <%= find_time(@blog.updated_at) %>
  </p>

    <br>
  <p>
    <strong>Category:</strong>
    <%= @blog.category.present? ? @blog.category.name : "No Category Till now."%>
  </p>
    <br>
  <p>
    <strong>Tags:</strong>
    <% @blog.tags.each do |t| %>
      <%= link_to t.name, show_blogs_tag_path(:tag_id => t.id), class:"badge badge-secondary"%>
    <% end %>
  </p>

  <p class="lead">
    <% if @blog.images.attached? %>
      <% @blog.images.each do |image| %>
        <%= image_tag thumbnail(image)%>
      <% end %>
    <% else %> 
      <%= "No Images Attached"%>
    <%end%>
  </p>
  <br>
  <p class="lead"><%= @blog.body%></p>
  <br>
  <br>
  <div>
    <input type="button" id="btn" class="btn btn-outline-primary" value="<%=@blog.likes.count%> Likes">
  </div>

  <% like = current_user.likes.find_by(blog: @blog) %>

  <div id="Create" style="display:none">
    <% @blog.likes.each do |l| %>
      <p><%= l.user.email %> </p>
    <% end %>
  </div>
  
  <% if like.nil? %>
    <%= button_to "Like",likes_path,params:{like:{blog_id: @blog.id}},method: :post%>
  <% else %>
    <%= button_to "Unlike",like_path(like),method: :delete %>
  <% end %>

  <p>
    <strong>Comments:</strong>
    <%#= render @blog.comments %>
    <%= render @blog.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
    <%= render partial: 'comments/form', locals: {blog: @blog,parent: nil} %>
  </p>



  <%= link_to "Back", :back,:class => "text-light btn btn-secondary"%>  
  <% if @blog.user_id == current_user.id %>
  <%= link_to "Edit Blog", edit_blog_path(@blog),:class => "text-light btn btn-secondary"%>  

  <%= link_to "Delete Blog", @blog,:class => "text-light btn btn-danger", data:{method: :delete, confirm: "Are you Sure?"}%>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function () {
      $("#btn").click(function () {
          $("#Create").toggle();
      });
  });
</script>

app/views/blogs/show_category.html.erb
<%= render 'blogs/search_form.html.erb' %>

app/views/blogs/show_tag.html.erb
<%= render 'blogs/search_form.html.erb' %>