config/routes.rb
Rails.application.routes.draw do
  resources :hobbies
  resources :blog_tags
  resources :tags
  resources :categories
  resources :likes, only: [:create, :destroy]
  resources :blogs do
    resources :comments, only: [:create]
  end
  devise_for :users
  get 'blogs/categories/:category_id', to: 'blogs#show_category', as: :show_blogs_category
  get 'blogs/tags/:tag_id', to: 'blogs#show_tag', as: :show_blogs_tag

  root 'blogs#index'

  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
  has_many :likes
  has_many :comments
  has_many :hobbies
  accepts_nested_attributes_for :hobbies, reject_if: ->(attributes){ attributes['name'].blank? }, allow_destroy: true

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
    before_action :set_user, only: %i[ show edit update destroy ]
  
    # GET /users or /users.json
    def index
      @users = User.all
    end
  
    # GET /users/1 or /users/1.json
    def show
    end
  
    # GET /users/new
    def new
      @user = User.new
    end
  
    # GET /users/1/edit
    def edit
    end
  
    # POST /users or /users.json
    def create
      @user = User.new(user_params)
  
      respond_to do |format|
        if @user.save
          format.html { redirect_to [:admin,@user], notice: "user was successfully created." }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /users/1 or /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to [:admin,@user], notice: "user was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /users/1 or /users/1.json
    def destroy
      @user.destroy
  
      respond_to do |format|
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit(:name,:email,:role,hobbies_attributes:[:name,:id,:_destroy])
      end
  end
  

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin,user]) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>  

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

    <% @user.hobbies.each_with_index do |hobby, i| %>
      <div class="field">
        <input type="hidden" value="<%= hobby.id %>" name= "user[hobbies_attributes][<%= i %>][id]" >
        <label>Hobby#<%= i+1 %>: 
          <input type="text" value="<%= hobby.name %>" name= "user[hobbies_attributes][<%= i %>][name]" >
        </label>
        <input type="hidden" value="false" name= "user[hobbies_attributes][<%= i %>][_destroy]" >
        <input type="checkbox" value="true" name= "user[hobbies_attributes][<%= i %>][_destroy]" >
      </div>
    <% end %>
    <label>New Hobby: 
      <input type="text" value="" name= "user[hobbies_attributes][<%= @user.hobbies.count %>][name]" >
    </label>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', [:admin,@user] %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New user', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/admin/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>