config/routes.rb
Rails.application.routes.draw do
  resources :hobbies
  resources :blog_tags
  resources :tags
  resources :categories
  resources :likes, only: [:create, :destroy]
  resources :blogs do
    resources :comments, only: [:create]
  end
  devise_for :users
  get 'blogs/categories/:category_id', to: 'blogs#show_category', as: :show_blogs_category
  get 'blogs/tags/:tag_id', to: 'blogs#show_tag', as: :show_blogs_tag

  root 'blogs#index'

  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

    validates :title, presence: true, uniqueness: { case_sensitive: true }, length: {maximum: 50, minimum:5}
    validates :body, presence: true, uniqueness: { case_sensitive:  true }, length: { minimum: 10 }
    validate :correct_image_type

    belongs_to :user
    belongs_to :category
    has_many_attached :images

    has_many :blog_tags
    has_many :tags, through: :blog_tags

    has_many :likes
    has_many :comments

    def correct_image_type
        if images.attached? == false
            errors.add(:images, "are missing")
        end

        images.each do |image|
            if !image.content_type.in?(%w(image/jpeg image/png))
                errors.add(:image,"must be a JPG/JPEG/PNG")
            end
        end
    end
#   accepts_nested_attributes_for :tag, allow_destroy: true

    def tags_attributes=(tags_attributes)
        tags_attributes.values.each do |tag|
            if !tag[:name].empty?
                self.tags << Tag.find_or_create_by(name: tag[:name])
            end
        end
    end
end

app/models/blog_tag.rb
class BlogTag < ApplicationRecord
    belongs_to :blog
    belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :blogs
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
end

app/models/hobby.rb
class Hobby < ApplicationRecord
    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :blog_id}

  belongs_to :user
  belongs_to :blog
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :blog_tags
    has_many :blogs, through: :blog_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
  has_many :likes
  has_many :comments
  has_many :hobbies
  accepts_nested_attributes_for :hobbies, reject_if: ->(attributes){ attributes['name'].blank? }, allow_destroy: true

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @q = Blog.ransack(params[:q])
    @blogs = @q.result(distinct: true).order(id: :desc).paginate(:page => params[:page], :per_page => 3)

    # @blogs = Blog.all
    @categories = Category.all
    @tags = Tag.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  def show_category
    @categories = Category.all
    @tags = Tag.all
    # @category = Category.where(id: params[:category_id]).first
    @category = Category.find(params[:category_id]) 
    @q = @category.blogs.ransack(params[:q])
    @blogs = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 3)
  end

  def show_tag
    @categories = Category.all
    @tags = Tag.all
    # @tag = Tag.where(id: params[:tag_id]).first
    @tag = Tag.find(params[:tag_id]) 
    @q = @tag.blogs.ransack(params[:q])
    @blogs = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 3)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    @blog.tags.build
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    if (@blog.user_id == current_user.id || current_user.role == "ADMIN")
      respond_to do |format|
        if @blog.update(blog_params)
          format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
          format.json { render :show, status: :ok, location: @blog }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to blogs_path,notice:"You are not allowed to edit this blog."
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :category_id,images: [],tags_attributes: [:id,:name], tag_ids: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def thumbnail(image)
        image.variant(resize: '500x500').processed
    end

    def find_time(t)
        a = t.in_time_zone(TZInfo::Timezone.get('Asia/Kolkata'))
        a.strftime("at %I : %M %p")
    end
     
    def find_date(d)
        d.strftime("%d %b, %y") 
    end

    def format_category(c,a)
        "#{c}  (#{a})"
    end
end

app/helpers/blog_tags_helper.rb
module BlogTagsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_alerts.html.erb
<div  id = "successMessage" class="alert alert-warning alert-dismissible fade show" role="alert">
<% if notice %>
  <%= notice %>
<% end %>
<% if alert %>
  <%= alert %>
<% end %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-dark" href="#">blogapplication.com</a>
    &trade;
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_header.html.erb
<style>
.m0{
  margin:0
}
.dropbtn {
  background-color: #3498DB;
  color: white;
  padding: 8px;
  font-size: 16px;
  border-radius: 5px;
  border: none;
  cursor: pointer;
}
.dropdown-menu{
  z-index: 9999;
  max-height:400px;
  overflow:scroll;
}

.dropbtn:hover, .dropbtn:focus {
  background-color: #2980B9;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  overflow: auto;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown a:hover {
  background-color: #17a2b8;
  color :white;
  }

.show {display: block;}
.search-bar{
  background-color: #141517;
  color: white;
  border: none;
}
.search-btn{
  background-color: #3498db;
  color: white;
}
.drop-btn{
  margin: 0px 15px;
}
#q_title_or_body_cont {
    background-color: black;
color: whitesmoke;
}

</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark NavPos">
  <div class="container-fluid">
    <%= link_to 'Blog Application', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">

      <ul  id="navMenus" class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in?%>
          <li class = "nav-item">
            <%= link_to "Blogs", blogs_path, class:"nav-link lh-1"%>
          </li>      
          <li class = "nav-item">
            <%= link_to 'Write a Blog', new_blog_path, class: 'nav-link lh-1' %>
          </li>
          <% if params[:controller] == 'blogs' && (params[:action] == 'index' || params[:action] == 'show_tag' || params[:action] == 'show_category') %>
            <%= search_form_for @q do |f| %>
              <li class="input-group">
                  <%= f.search_field :title_or_body_cont ,placeholder:"search blog title/body",class:"form-control search-bar" %>
                  <%= f.button fa_icon("search"), class: "btn search-btn", id: "register-button" %>
              </li>
            <% end %>
          <% end %>
                  
          <li class = "mx-2 nav-item dropdown">
            <button onclick="myFunction()" class="dropbtn lh-1"><%= "Categories"%> | <i class="fa-solid fa-angle-down"></i></button>
            <div id="myDropdown" class="dropdown-menu dropdown-content">
              <%= link_to 'Add New Category', new_category_path, class: 'btn btn-outline-info drop-btn p-2'%>
              <hr/>
              <% Category.all.each do |c|%>
                <p class="m0">
                <%= link_to format_category(c.name,c.blogs.count), show_blogs_category_path(:category_id => c.id), class:'cat-link dropdown-item' %>
                </p>
              <% end %>
            </div>    
          </li>      
          <li class = "nav-item">
          <%= link_to "Tags", tags_path, class:"nav-link"%>
          </li>  
        </ul> 
          <div class="dropdown">
            <button onclick="myFunction2()" class="dropbtn"><%= current_user.email%> | <i class="fa-solid fa-angle-down"></i></button>
            <div id="myDropdown2" class="dropdown-menu dropdown-content">
              <%= link_to "Edit Profile", edit_user_registration_path,class:"dropdown-item"%>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete,class:"dropdown-item"%>
            </div>
          </div>       
        <% else %>
          <li class = "nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
          </li>        
          <li class = "nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
          </li>        
        </ul>
        <% end %>

    </div>
  </div>
</nav>

<script>
/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
  if (document.getElementById("myDropdown2").classList.contains("show")){
    document.getElementById("myDropdown2").classList.remove("show")
  }
}
function myFunction2() {
  document.getElementById("myDropdown2").classList.toggle("show");
  if (document.getElementById("myDropdown").classList.contains("show")){
    document.getElementById("myDropdown").classList.remove("show")
  }
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# font-awesome cdn %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%# Bootstrap %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# add jquery %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        
    <style>
    .active {
    background-color:rgb(40, 167, 69);
    color:white;
    border-radius:5px;
    }
    .NavPos{
    position: fixed;
    top: 0;
    width: 100%;
    z-index: 999;
    }
    .card{
      position: inherit !important;
      width: max-content !important;
    }
    </style>
  </head>

  <body>
    <%= render "layouts/header"%>
    <div class = "container mt-5"> 
      <br>
      <% if notice || alert%>
        <%= render "layouts/alerts"%>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer"%>
  </body>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<%# add jquery and script for active navbar elements %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>
  var loc = window.location.pathname;
  console.log(loc);
  $('#navMenus').find('a').each(function() {
  $(this).toggleClass('active', $(this).attr('href') === loc);
  });

  // fade the notice out after 2 seconds
  window.setTimeout("document.querySelector('#successMessage').style.display='none';", 2000);; 
</script>
</html>